version: '3'
services:
  mysql: 
    image: mysql:5.7
    ports:
      -'33061:3306'
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=symfony